---
title: "ADA Abstract"
author: "Windy Wang"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
ds <- readRDS(file='../data/ds.Rds')
ds1 <- ds %>% filter(fVN == "Baseline")
source('../R/functions.r')

library(nephro)
library(carpenter)
library(ggplot2)
library(knitr)
library(plyr)
library(dplyr)
library(tidyr)
library(pander)
library(captioner)
library(knitr)
library(mason)
library(msm)
library(gee)
library(magrittr)
library(lme4)
library(lmerTest)
library(geepack)
```

Subject Characterization
========================

Subject characteristics across visit numbers
```{r subject characteristics}
table_subChar(ds)

## check n
table(ds$fVN)
```

Statististical tests
```{r stats}

## make sure that it is okay to do chi-square with longitudinal
## make sure the error term for anova is correct

summary(aov(Age ~ fVN + Error(SID/fVN), data=ds))

chisq.test(table(ds$Ethnicity, ds$fVN), correct = TRUE)

chisq.test(table(ds$Sex, ds$fVN), correct = TRUE)

summary(aov(BMI ~ fVN + Error(SID/fVN), data=ds))

summary(aov(Waist ~ fVN + Error(SID/fVN), data=ds))

summary(aov(eGFR ~ fVN + Error(SID/fVN), data=ds))

summary(aov(ACR ~ fVN + Error(SID/fVN), data=ds))

summary(aov(UrineCreatinine ~ fVN + Error(SID/fVN), data=ds))

summary(aov(UrineMicroalbumin ~ fVN + Error(SID/fVN), data=ds))

summary(aov(UDBP ~ fVN + Error(SID/fVN), data=ds))

summary(aov(Creatinine ~ fVN + Error(SID/fVN), data=ds))

summary(aov(VitaminD ~ fVN + Error(SID/fVN), data=ds))

summary(aov(PTH ~ fVN + Error(SID/fVN), data=ds))

summary(aov(ALT ~ fVN + Error(SID/fVN), data=ds))

summary(aov(Systolic ~ fVN + Error(SID/fVN), data=ds))

summary(aov(Diastolic ~ fVN + Error(SID/fVN), data=ds))

summary(aov(MeanArtPressure ~ fVN + Error(SID/fVN), data=ds))

summary(aov(Glucose0 ~ fVN + Error(SID/fVN), data=ds))

summary(aov(Glucose120 ~ fVN + Error(SID/fVN), data=ds))

chisq.test(table(ds$dm_status, ds$fVN), correct = TRUE)

# TukeyHSD(anova, which="fVN")
```


Part 1 - Cross-Sectional
========================

ACR
---
```{r acr boxplot}

# Box plot of uVDBP in different albuminuria categories

ds %>% 
  filter(fVN == "Baseline") %>% 
  select(acr_status, udbpCrRatio) %>%
  na.omit() %>%
  box_plot("acr_status", "log(udbpCrRatio)", 
            "Albuminuria",
            "log uVDBP:Creatinine")

# Boxplot of ACR in uVDBP categories
ds1 %>% 
  select(UDBP_status, ACR) %>% 
  na.omit() %>% 
  box_plot("UDBP_status", "log(ACR)",
           "Urinary VDBP status",
           "log urine albumin-to-creatinine ratio (mg/mmol)")

# ANOVA

anova <- aov(formula = log(udbpCrRatio)~acr_status, data = ds1)
summary(anova)
TukeyHSD(anova)
rm(anova)
```

```{r acr scatterplot}

# Scatterplot of ACR and uVDBP ----------------------------------

ds %>% 
  filter(fVN == "Baseline") %>% 
  select(ACR, udbpCrRatio) %>% 
  na.omit() %>% 
  scatter_plot("log(ACR)", "log(udbpCrRatio)",
               "log Albumin:Creatinine Ratio",
               "log UDBP:Creatinine") +
  geom_smooth(method = lm, colour = "grey50")

# Spearman Correlation ------------------------------------------

ds %>% 
  filter(fVN == "Baseline") %>% 
  cor.test(formula = ~ ACR + udbpCrRatio, data = ., method = "spearman")
```


eGFR
----
```{r eGFR boxplot}

# Boxplot of uVDBP concentrations across eGFR categories --------------

ds %>% 
  filter(fVN == "Baseline") %>% 
  select(eGFR_status, udbpCrRatio) %>% 
  na.omit() %>% 
  box_plot2("eGFR_status", "log(udbpCrRatio)", 
            "Estimated GFR (ml/min/1.73m^2)",
            "log uVDBP:Creatinine")

# Boxplot of eGFR in uVDBP categories
ds1 %>% 
  select(UDBP_status, eGFR) %>% 
  na.omit() %>% 
  box_plot("UDBP_status", "eGFR",
           "Urinary VDBP status",
           "Estimated glomerular filtration rate (ml/min/1.73m^2)")

# ANOVA

anova <- aov(formula = log(udbpCrRatio)~eGFR_status, data = ds1)
summary(anova)
TukeyHSD(anova)
rm(anova)
```

```{r eGFR scatterplot}

# Scatterplot of ACR and uVDBP ----------------------------------

ds %>% 
  filter(fVN == "Baseline") %>% 
  select(eGFR, udbpCrRatio) %>% 
  na.omit() %>% 
  scatter_plot("eGFR", "log(udbpCrRatio)",
               "Estimated Glomerular Filtration Rate (ml/min/1.73m^2)",
               "log UDBP:Creatinine") +
  geom_smooth(method = lm, colour = "grey50")

# Spearman Correlation ------------------------------------------

ds %>% 
  filter(fVN == "Baseline") %>% 
  cor.test(formula = ~ eGFR + udbpCrRatio, data = ., method = "spearman")
```

Glycemic Status
---------------
```{r dm boxplot}

# Boxplot of uVDBP concentrations across DM categories --------------

ds %>% 
  filter(fVN == "Baseline") %>% 
  select(dm_status, udbpCrRatio) %>% 
  na.omit() %>% 
  box_plot("dm_status", "log(udbpCrRatio)", 
            "Estimated GFR (ml/min/1.73m^2)",
            "log uVDBP:Creatinine")

# Boxplot of Glucose0 in uVDBP categories
ds1 %>% 
  select(UDBP_status, Glucose0) %>% 
  na.omit() %>% 
  box_plot("UDBP_status", "log(Glucose0)",
           "Urinary VDBP status",
           "Fasting Glucose")

# Boxplot of Glucose120 in uVDBP categories
ds1 %>% 
  select(UDBP_status, Glucose120) %>% 
  na.omit() %>% 
  box_plot("UDBP_status", "log(Glucose120)",
           "Urinary VDBP status",
           "2h-post OGTT")

# ANOVA---------------------------------------------------------------

anova <- aov(formula = log(udbpCrRatio)~dm_status, data = ds1)
summary(anova)
TukeyHSD(anova)
rm(anova)
```



25(OH)
------
```{r vitD scatterplot}

# Scatterplot of serum 25(OH)D and uVDBP ----------------------------------

ds %>% 
  filter(fVN == "Baseline") %>% 
  scatter_plot("log(udbpCrRatio)", "VitaminD",
               "log uVDBP:creatinine",
               "Serum 25(OH)D") +
  geom_smooth(method = lm, colour = "grey50")

# Spearman correlation ----------------------------------------------------

ds %>% 
  filter(fVN == "Baseline") %>% 
  cor.test(formula = ~ udbpCrRatio + VitaminD, data = ., method = "spearman")
```


Part 2 - GEE
============
```{r mason}

ds %>% 
  dplyr::mutate(udbpBase = ifelse(fVN == "Baseline", UDBP, NA),
                ageBase = ifelse(fVN == "Baseline", Age, NA),
                vitdBase = ifelse(fVN == "6Year", NA, VitaminD),
                Ethnicity = factor(Ethnicity, ordered = FALSE)) %>% 
  dplyr::arrange(SID, fVN) %>% 
  dplyr::group_by(SID) %>% 
  tidyr::fill(udbpBase, ageBase, vitdBase) %>% 
  dplyr::ungroup() %>% 
  mason::design("gee") %>% 
  mason::add_settings(family = stats::gaussian(),
                      corstr = "ar1", cluster.id = "SID") %>% 
  mason::add_variables("yvars", c("ACR", "eGFR", "VitaminD", "vitdBase")) %>% 
  mason::add_variables("xvars", "udbpBase") %>% 
  mason::add_variables("covariates", c("VN", "ageBase", "Sex", "Ethnicity")) %>% 
  mason::construct() %>% 
  mason::scrub() %>% 
  mason::polish_adjust_pvalue(method = "BH") %>% 
  dplyr::mutate_each(dplyr::funs(format_rounding), estimate, std.error, conf.low, conf.high) %>% 
  dplyr::mutate_each(dplyr::funs(format_p), p.value, adj.p.value)

# To-Do: categorical outcome variables

```


Part 3 - Disease Progression (probably no time)
===============================================

Find n
```{r}
# ds %>% 
#   dplyr::select(SID, VN, eGFR_status, eGFR) %>% 
#   dplyr::group_by(SID, VN) %>% 
#   na.omit() %>% 
#   statetable.msm(eGFR_status, SID, data= .)

```


