---
title: Urinary excretion of vitamin D binidng protein across varying degrees of kidney
  dysfunction and dysglycemia
author: "WINDY WANG"
date: "July 6, 2016"
# bibliography: bibliography.bib
output:
 word_document
    # reference_docx: ../docx_template.docx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE)
knitr::opts_knit$set(root.dir = '../')
```

```{r package}
library(nephro)
library(carpenter)
library(ggplot2)
library(knitr)
library(plyr)
library(dplyr)
library(tidyr)
library(pander)
library(captioner)
library(knitr)
```

```{r data}
ds <- readRDS(file='data/ds.Rds')
source('R/functions.r')
```

# Values
```{r eGFR}
ds_base <- ds %>% 
  filter(VN == 1, UDBP < 5000)

ds %>% 
  filter(VN == 1, UDBP < 5000) %>% 
  select(dm_status, udbpCrRatio) %>% 
  na.omit() %>% 
  group_by(dm_status) %>% 
  summarise(Median = median(log(udbpCrRatio)),
            Lower = quantile(log(udbpCrRatio), probs = 0.25),
            Upper = quantile(log(udbpCrRatio), probs = 0.75)) %>% 
  knitr::kable()
  
anova <- aov(log(ds_base$udbpCrRatio) ~ ds_base$mcr_status)
summary(anova)
TukeyHSD(anova)

rm(anova)
rm(ds_base)
```


# Graphs

Boxplot: eGFR categories

```{r box-eGFR}
ds_base <- ds %>% 
  filter(VN == 1, UDBP < 5000)

ds_base %>% 
  select(eGFR_status, UDBP, UrineCreatinine) %>% 
  na.omit() %>% 
  box_plot2("eGFR_status", "log(UDBP/UrineCreatinine)", 
            "Estimated GFR (ml/min/1.73m^2)",
            "log uVDBP:Creatinine") +
  scale_x_discrete(labels = paste(levels(ds_base$eGFR_status), 
                                    "\n(n=", table(ds_base$eGFR_status), ")", sep = ""))

anova <- aov(log(ds_base$UDBP/ds_base$UrineCreatinine)~ds_base$eGFR_status)
summary(anova)
# TukeyHSD(anova)
# 
# kruskal.test(ds_base$UDBP ~ ds_base$eGFR_status) 

rm(ds_base)
rm(anova)
```

Scatterplot: eGFR categories
```{r scatter-eGFR}
ds_base <- ds %>% 
  filter(VN == 1, UDBP < 5000)

ds_base %>% 
  ggplot(aes_string("eGFR", "log(UDBP/UrineCreatinine)")) +
  geom_point() + #mapping = aes(colour = CRP)
  xlab("Estimated GFR (ml/min/1.73m^2)") + 
  ylab("log UDBP:Creatinine") +
  geom_smooth(method = lm, colour = "black") +
  theme(panel.background = element_blank())
  
cor.test(ds_base$eGFR, ds_base$udbpCrRatio, method = "spearman", exact = FALSE)

rm(ds_base)
```


Boxplot: MCR categories
```{r box-mcr}
ds_base <- ds %>% 
  filter(VN == 1, UDBP < 5000, CRP < 10)

ds_mcr <- ds %>% 
  mutate(mcr_cat = ifelse(mcr_status == "Normal", "Normal", "Albuminuria")) %>% 
  mutate(mcr_cat = factor(mcr_cat,
                          levels = c("Normal", "Albuminuria"),
                          ordered = TRUE)) %>% 
  filter(VN == 1, UDBP < 5000, CRP < 10)

ds_mcr %>% 
  filter(UDBP < 5000, CRP < 10) %>% 
  select(mcr_cat, UDBP, UrineCreatinine) %>% 
  na.omit() %>% 
  box_plot2("mcr_cat", "log(UDBP/UrineCreatinine)", 
            "Albuminuria",
            "log uVDBP:Creatinine") +
  scale_x_discrete(labels = paste(levels(ds_mcr$mcr_cat), 
                                    "\n(n=", table(ds_mcr$mcr_cat), ")", sep = ""))

anova <- aov(ds_mcr$UDBP~ds_mcr$mcr_status)
summary(anova)
TukeyHSD(anova)

kruskal.test(ds_base$UDBP ~ ds_base$mcr_status) 

rm(ds_base)
rm(ds_mcr)
rm(anova)
```

Scatterplot: MCR categories
```{r scatter-mcr}
ds_base <- ds %>% 
  filter(VN == 1, UDBP < 5000)

ds_base %>% 
  select(MicroalbCreatRatio, UDBP, UrineCreatinine) %>% 
  na.omit() %>% 
  scatter_plot("log(MicroalbCreatRatio)", "log(UDBP/UrineCreatinine)",
               "log Microalbumin:Creatinine Ratio",
               "log UDBP:Creatinine") +
  geom_smooth(method = lm, colour = "black")

cor.test(ds_base$MicroalbCreatRatio, ds_base$udbpCrRatio, 
         method = "spearman", exact = FALSE)

rm(ds_base)
```

Boxplot: DM categories
```{r box-DM}
ds_base <- ds %>% 
  filter(VN == 1, UDBP < 5000, CRP < 10)

ds_base %>% 
  select(dm_status, UDBP, UrineCreatinine) %>% 
  na.omit() %>% 
  box_plot2("dm_status", "log(UDBP/UrineCreatinine)", 
            "Glycemic Status",
            "log uVDBP:Creatinine") +
  scale_x_discrete(labels = paste(levels(ds_base$dm_status), 
                                  "\n(n=", table(ds_base$dm_status), ")", sep = ""))

anova <- aov(ds_base$udbpCrRatio~ds_base$dm_status)
summary(anova)
TukeyHSD(anova)

# kruskal.test(ds_base$UDBP ~ ds_base$mcr_status) 

rm(anova)
rm(ds_base)
```

Scatterplot: Fasting glucose
```{r}
ds %>% 
  filter(VN == 1) %>% 
  filter(UDBP < 5000) %>% 
  select(Glucose0, UDBP, UrineCreatinine) %>% 
  na.omit() %>% 
  scatter_plot("Glucose0", "log(UDBP/UrineCreatinine)",
               "Fasting Glucose (mmol/L)",
               "log UDBP:Creatinine") +
  geom_smooth(colour = "black")
```

Scatterplot: 2h OGTT
```{r}
ds %>% 
  filter(VN == 1) %>% 
  filter(UDBP < 5000) %>% 
  select(Glucose120, UDBP, UrineCreatinine) %>% 
  na.omit() %>% 
  scatter_plot("Glucose120", "log(UDBP/UrineCreatinine)",
               "2h Post-OGTT Blood Glucose (mmol/L)",
               "log UDBP:Creatinine") +
  geom_smooth(colour = "black")
```

Scatterplot: 25(OH)D
```{r scatter-vitD}
ds_base <- ds %>% 
  filter(VN == 1, UDBP < 5000)

ds_base %>% 
  scatter_plot("log(UDBP/UrineCreatinine)", "log(VitaminD)",
               "log UDBP:Creatinine",
               "log serum 25(OH)D") +
  geom_smooth(method = lm, colour = "black")

cor.test(ds_base$VitaminD, ds_base$udbpCrRatio, method = "spearman", exact = FALSE)

rm(ds_base)
```

Subgroup analysis: 25(OH)D and UDBP
```{r}
# Determine PTH tertiles (<3.61, 3.61 - 5.0, >5.0)
# Vitamin D status - Endocrine Society:
#     Deficient = <50 nmol/L
#     Insufficient = 50-74
#     Sufficient = >74

ds %>% 
  filter(VN == 1, UDBP < 5000) %>% 
  summarise(Lower = quantile(PTH, probs = 0.33, na.rm = TRUE),
            Upper = quantile(PTH, probs = 0.67, na.rm = TRUE))

ds_sub <- ds %>% 
  filter(VN == 1, UDBP < 5000) %>% 
  mutate(dm_status2 = ifelse(dm_status == "NGT", "NGT",
                              "Dysglycaemia"),
         mcr_status2 = ifelse(mcr_status == "Normal", "Normal",
                              "Albuminuria"),
         eGFR_status2 = ifelse(eGFR_status == "Normal" | eGFR_status == "Hyperfiltration",
                               "Normal", "KD"),
         lowVitD = ifelse()) %>% 
  filter(mcr_status2 == "Albuminuria", eGFR_status2 == "KD")

ds_sub %>% 
  scatter_plot("log(UDBP/UrineCreatinine)", "VitaminD",
               "log UDBP:Creatinine",
               "Serum 25(OH)D (nmol/L)") +
  geom_smooth(method = "lm", colour = "black")

cor.test(ds_sub$VitaminD, ds_sub$UDBP, method='spearman', exact=FALSE)

rm(ds_sub)
```

Medication
```{r}
ds_visit <- ds %>% 
  filter(fVN == "Baseline", UDBP < 5000, CRP < 10) %>% 
  select(fMedsBP, UDBP, UrineCreatinine, dm_status) %>% 
  na.omit() %>% 
  group_by(fMedsBP, dm_status) %>% 
  mutate(n = ifelse(row_number()==n(), paste("n =", n()), NA))

ds_visit %>% 
  box_plot2("fMedsBP", "log(UDBP/UrineCreatinine)",
            "Blood Pressure Medication", "log uVDBP:Creatinine") +
  # scale_x_discrete(labels = paste(levels(ds_visit$fMedsBloodPressure),
  #                                 "\n(n=", table(ds_visit$eGFR_status), ")", sep = "")) +
  facet_grid(~dm_status, switch = "x") +
  geom_text(aes(label = n), y = -4, size = 3, colour = "grey40")

rm(ds_visit)
```


