---
title: "Progression of Disease"
author: "Windy Wang"
date: "November 3, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
ds <- readRDS(file='../data/ds.Rds')
source('../R/functions.r')

library(nephro)
library(carpenter)
library(ggplot2)
library(knitr)
library(plyr)
library(dplyr)
library(tidyr)
library(pander)
library(captioner)
library(knitr)
library(mason)
library(msm)
library(gee)
```

Abstract
--------

This document examines the progression and regression of kidney dysfunction using the 
urinary albumin-to-creatinine ratio (ACR).


Find n
------
```{r}
## msm package
ds_msm <- ds %>% 
  dplyr::select(SID, VN, acr_status) %>% 
  dplyr::group_by(SID, VN) %>% 
  na.omit() 

statetable.msm(acr_status, SID, data=ds_msm)


ds1 <- ds %>% 
  filter(VN == 1) %>% 
  select(ACR, acrProgress1) %>% 
  na.omit()

table(ds1$acrProgress1)

## Total: 494

rm(ds1)

## -------------------------------------------------------------------------------------------

ds3 <- ds %>% 
  filter(VN == 6) %>% 
  select(ACR, acrProgress2)

table(ds3$acrProgress2)

## total: 453

rm(ds3)

## -------------------------------------------------------------------------------------------

ds_noReg <- ds %>% 
  mutate(acr1_noReg = ifelse(acrProgress1 == "Progress", "Progress",
                             "No change"),
         acr2_noReg = ifelse(acrProgress2 == "Progress", "Progress",
                             "No change"))

ds1 <- ds_noReg %>% 
  filter(VN == 1)
  
table(ds1$acr1_noReg)

rm(ds1)

############

ds3 <- ds_noReg %>% 
  filter(VN == 3)
  
table(ds3$acr2_noReg)

rm(ds3)

## -------------------------------------------------------------------------------------------

ds_total <- ds %>% 
  # filter(VN == 3) %>% 
  select(SID, VN, acr_status, acrProgress1, acrProgress2, acrProgress)

table(ds_total$acrProgress)

table(ds$acrProgress)
```


Values Across Categories
```{r table1}
# Baseline measurements for subjects whose disease status changed between baseline 
# and 3-year follow-up.

table <- ds %>% 
  dplyr::filter(VN == 1) %>%
  dplyr::group_by(acrProg1_3) %>% 
  dplyr::summarise(
    n = n(),
    Age = paste0(round(mean(Age, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(Age, na.rm = TRUE), 1), 
                     ")"),
    BMI = paste0(round(mean(BMI, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(BMI, na.rm = TRUE), 1), 
                     ")"),
    Waist = paste0(round(mean(Waist, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(Waist, na.rm = TRUE), 1), 
                     ")"),
    ACR = paste0(round(mean(MicroalbCreatRatio, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(MicroalbCreatRatio, na.rm = TRUE), 1), 
                     ")"),
    eGFR = paste0(round(mean(eGFR, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(eGFR, na.rm = TRUE), 1), 
                     ")"),
    UDBP = paste0(round(mean(UDBP, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(UDBP, na.rm = TRUE), 1), 
                     ")"),
    VitD = paste0(round(mean(VitaminD, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(VitaminD, na.rm = TRUE), 1), 
                     ")")
  )
  # tidyr::spread(acrProg1_3, n)


tableWord <- as.data.frame(t(table))
```

```{r table2}
## Baseline measurements for subjects whose disease status changed between baseline 
## and 3-year follow-up (NO SUBCATEGORIES).

table <- ds %>% 
  dplyr::filter(VN == 1) %>%
  dplyr::group_by(acrProgress1) %>% 
  dplyr::summarise(
    n = n(),
    Age = paste0(round(mean(Age, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(Age, na.rm = TRUE), 1), 
                     ")"),
    BMI = paste0(round(mean(BMI, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(BMI, na.rm = TRUE), 1), 
                     ")"),
    Waist = paste0(round(mean(Waist, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(Waist, na.rm = TRUE), 1), 
                     ")"),
    ACR = paste0(round(mean(MicroalbCreatRatio, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(MicroalbCreatRatio, na.rm = TRUE), 1), 
                     ")"),
    eGFR = paste0(round(mean(eGFR, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(eGFR, na.rm = TRUE), 1), 
                     ")"),
    UDBP = paste0(round(mean(UDBP, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(UDBP, na.rm = TRUE), 1), 
                     ")"),
    VitD = paste0(round(mean(VitaminD, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(VitaminD, na.rm = TRUE), 1), 
                     ")")
  )
  # tidyr::spread(acrProg1_3, n)


tableWord <- as.data.frame(t(table))

## ANOVA -------------------------------------------------------------------------------------
anova <- aov(ds$Waist~ds$acrProgress1)
summary(anova)
TukeyHSD(anova)
```

```{r table3}
# Baseline measurements for subjects whose disease status changed between 3-year 
# and 6-year follow-up.

table <- ds %>% 
  dplyr::filter(VN == 1) %>%
  dplyr::group_by(acrProg3_6) %>% 
  dplyr::summarise(
    n = n(),
    Age = paste0(round(mean(Age, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(Age, na.rm = TRUE), 1), 
                     ")"),
    BMI = paste0(round(mean(BMI, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(BMI, na.rm = TRUE), 1), 
                     ")"),
    Waist = paste0(round(mean(Waist, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(Waist, na.rm = TRUE), 1), 
                     ")"),
    ACR = paste0(round(mean(MicroalbCreatRatio, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(MicroalbCreatRatio, na.rm = TRUE), 1), 
                     ")"),
    eGFR = paste0(round(mean(eGFR, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(eGFR, na.rm = TRUE), 1), 
                     ")"),
    UDBP = paste0(round(mean(UDBP, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(UDBP, na.rm = TRUE), 1), 
                     ")"),
    VitD = paste0(round(mean(VitaminD, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(VitaminD, na.rm = TRUE), 1), 
                     ")")
  )


tableWord <- as.data.frame(t(table))
```

```{r table4}
## Baseline measurements for subjects whose disease status changed between 3-year 
## and 6-year follow-up (NO SUBCATEGORIES).

table <- ds %>% 
  dplyr::filter(VN == 1) %>%
  dplyr::group_by(acrProgress2) %>% 
  dplyr::summarise(
    n = n(),
    Age = paste0(round(mean(Age, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(Age, na.rm = TRUE), 1), 
                     ")"),
    BMI = paste0(round(mean(BMI, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(BMI, na.rm = TRUE), 1), 
                     ")"),
    Waist = paste0(round(mean(Waist, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(Waist, na.rm = TRUE), 1), 
                     ")"),
    ACR = paste0(round(mean(MicroalbCreatRatio, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(MicroalbCreatRatio, na.rm = TRUE), 1), 
                     ")"),
    eGFR = paste0(round(mean(eGFR, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(eGFR, na.rm = TRUE), 1), 
                     ")"),
    UDBP = paste0(round(mean(UDBP, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(UDBP, na.rm = TRUE), 1), 
                     ")"),
    VitD = paste0(round(mean(VitaminD, na.rm = TRUE), 1), 
                     " (", 
                     round(sd(VitaminD, na.rm = TRUE), 1), 
                     ")")
  )


tableWord <- as.data.frame(t(table))

## Boxplot -----------------------------------------------------------------------------------
boxplot(ds$UDBP~ds$acrProgress2)

## ANOVA -------------------------------------------------------------------------------------
anova <- aov(ds$VitaminD~ds$acrProgress1)
summary(anova)
TukeyHSD(anova)
```

Check Missingness
-----------------
```{r missing}
dsMissing <- ds %>% 
  dplyr::select(SID, VN, MicroalbCreatRatio, ACR, 
                UrineCreatinine, UrineMicroalbumin) %>% 
  dplyr::group_by(SID, VN) %>% 
  dplyr::filter(!is.na(MicroalbCreatRatio))

dsMissing2 <- ds %>% 
  dplyr::select(SID, VN, MicroalbCreatRatio, ACR, MicroalbCreatRatio,
                ALT, Creatinine, 
                UrineCreatinine, UrineMicroalbumin) %>% 
  dplyr::group_by(SID, VN) %>% 
  dplyr::filter(is.na(ACR))
```

